name: React Native CI
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: React Native CI
    runs-on: [ubuntu-latest]
    steps:
      - name: git
        uses: actions/checkout@v2
      - name: setup npm
        uses: actions/setup-node@v1
      - name: install libs
        run: npm install
      - name: setup android env
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build package
        run: ./gradlew assembleDebug


