name: React Native CI
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: React Native CI
    runs-on: [ubuntu-latest]
    steps:
      - name: git
        uses: actions/checkout@v2
      - name: setup npm
        uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install libs
        run: npm install
      - name: setup android env
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: build package
        run: cd android && ./gradlew assembleDebug
      - name: upload apk
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk


